import { GitHubClient } from "./github";
import { FileFilter } from "./fileFilter";
import { ReviewerFactory } from "./reviewerFactory";
import { QuotaExceededError, APIError, extractErrorMessage } from "./errors";
import { loadConfig } from "./config";

const config = loadConfig();
// Initialize clients
const github = new GitHubClient(config.githubToken);
const fileFilter = new FileFilter("review-config.yml");
const reviewer = ReviewerFactory.createReviewer(config);

async function main() {
  const [owner, repo] = config.repo.split("/");
  console.log(`Processing PR #${config.prNumber} in ${owner}/${repo}`);

  // 1. Fetch PR diff
  console.log("Fetching PR files...");
  let files = await github.fetchPullRequestFiles(owner, repo, config.prNumber);
  if (files.length === 0) {
    console.log("No files found in PR.");
    return;
  }
  console.log(`Found ${files.length} files, filtering...`);
  files = fileFilter.filterFiles(files);
  if (files.length === 0) {
    console.log("No files to review after filtering.");
    return;
  }

  // Build diff
  const diff = files
    .map((f) => `### ${f.filename}\n\`\`\`\n${f.patch}\n\`\`\``)
    .join("\n\n");

  // 2. get review criteria
  const criteria = fileFilter.getFocusAreas();

  // 3. Call reviewer (OpenAI or Ollama based on config)
  console.log("Running AI review...");
  const response = await reviewer.review({
    diff,
    criteria,
  });
  console.log(`Review completed using model: ${response.model}`);
  console.log(
    `Tokens used: ${response.usage.promptTokens} prompt, ${response.usage.completionTokens} completion`,
  );

  // 4. Post comment on PR
  const reviewComment = `${response.content}\n\n---\n*Generated by AI PR Review Assistant*\n\nTokens used: ${response.usage.totalTokens}`;

  // Post comment
  console.log("Posting review comment...");
  await github.postReviewComment(owner, repo, config.prNumber, reviewComment);

  console.log("Review posted successfully.");
}

main().catch((error) => {
  if (error instanceof QuotaExceededError) {
    console.error("QUOTA_EXCEEDED: " + error.message);
    process.exit(1);
  }

  if (error instanceof APIError) {
    console.error("API_ERROR: " + error.message);
    if (error.statusCode) {
      console.error(`Status code: ${error.statusCode}`);
    }
    process.exit(1);
  }
  console.error("ERROR: " + extractErrorMessage(error));
  process.exit(1);
});
