import { loadConfig } from "./config";
import { GitHubClient } from "./github";
import { FileFilter } from "./fileFilter";
import { OpenAIReviewer } from "./openai";
import { QuotaExceededError, APIError, extractErrorMessage } from "./errors";

async function main() {
  try {
    // Load configuration
    const config = loadConfig();
    console.log(`Processing PR #${config.prNumber} in ${config.repo}`);

    // Initialize clients
    const github = new GitHubClient(config.githubToken);
    const fileFilter = new FileFilter("review-config.yml");
    const reviewer = new OpenAIReviewer(config.openaiApiKey);

    // Fetch PR files
    console.log("Fetching PR files...");
    let files = await github.fetchPullRequestFiles(
      config.owner,
      config.repo.split("/")[1],
      config.prNumber
    );

    if (files.length === 0) {
      console.log("No files found in PR.");
      return;
    }

    console.log(`Found ${files.length} files, filtering...`);
    files = fileFilter.filterFiles(files);

    if (files.length === 0) {
      console.log("No files to review after filtering.");
      return;
    }

    // Build diff
    const diff = files
      .map((f) => `### ${f.filename}\n\`\`\`\n${f.patch}\n\`\`\``)
      .join("\n\n");

    // Get review criteria
    const criteria = fileFilter.getFocusAreas();

    // Run AI review
    console.log("Running AI review...");
    const review = await reviewer.review({
      diff,
      criteria,
    });

    // Build comment
    const reviewComment = `${review.content}\n\n---\n*Generated by AI PR Review Assistant*\n\nTokens used: ${review.usage.totalTokens}`;

    // Post comment
    console.log("Posting review comment...");
    await github.postReviewComment(
      config.owner,
      config.repo.split("/")[1],
      config.prNumber,
      reviewComment
    );

    console.log("Review posted successfully.");
  } catch (error) {
    if (error instanceof QuotaExceededError) {
      console.error("QUOTA_EXCEEDED: " + error.message);
      process.exit(1);
    }

    if (error instanceof APIError) {
      console.error("API_ERROR: " + error.message);
      if (error.statusCode) {
        console.error(`Status code: ${error.statusCode}`);
      }
      process.exit(1);
    }

    console.error("ERROR: " + extractErrorMessage(error));
    process.exit(1);
  }
}

main();
