import { Octokit } from "@octokit/rest";
import OpenAI from "openai";
import * as fs from "fs";
import * as yaml from "js-yaml";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const [owner, repo] = (process.env.REPO || "").split("/");
const prNumber = parseInt(process.env.PR_NUMBER || "0");

async function main() {
  // 1. Fetch PR diff
  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number: prNumber,
  });

  const diff = files
    .filter((f) => !shouldIgnore(f.filename))
    .map((f) => `### ${f.filename}\n\`\`\`\n${f.patch || ""}\n\`\`\``)
    .join("\n\n");

  // 2. Load review config
  const config = yaml.load(
    fs.readFileSync("review-config.yml", "utf8")
  ) as any;

  const criteria = config.review.focus_areas.join("\n- ");

  // 3. Call OpenAI
  const response = await openai.chat.completions.create({
    model: "gpt-4o",
    messages: [
      {
        role: "system",
        content: `You are a senior software engineer reviewing a pull request. 
Review the diff below and evaluate it against these criteria:
- ${criteria}

Respond in this exact format:
## AI Review Summary
**Overall:** [one sentence summary]

### Blockers
[list any blocking issues, or write "None"]

### Suggestions
[list improvement suggestions]

### Nitpicks
[list minor style notes]`,
      },
      {
        role: "user",
        content: `Here is the PR diff:\n\n${diff}`,
      },
    ],
  });

  const reviewComment = response.choices[0].message.content || "";

  // 4. Post comment on PR
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: `${reviewComment}\n\n---\n*Generated by AI PR Review Assistant*`,
  });

  console.log("Review posted successfully here.");
}

function shouldIgnore(filename: string): boolean {
  const ignorePatterns = ["*.lock", "dist/", "*.generated.ts"];
  return ignorePatterns.some((p) => filename.includes(p.replace("*", "")));
}

main().catch(console.error);